services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    networks:
      - spring-net

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      STORAGE_TYPE: mem
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9411/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - spring-net

  discoveryserver:
    container_name: discoveryserver
    image: ${DOCKER_USERNAME}/discoveryserver:latest
    ports:
      - "8761:8761"
    volumes:
      - ./logs/discoveryserver:/logs
    environment:
      LOG_PATH: /logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - spring-net

  configserver:
    container_name: configserver
    image: ${DOCKER_USERNAME}/configserver:latest
    ports:
      - "8888:8888"
    depends_on:
      discoveryserver:
        condition: service_healthy
    volumes:
      - ./logs/configserver:/logs
    environment:
      LOG_PATH: /logs
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8761/eureka
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - spring-net

  apigateway:
    container_name: apigateway
    image: ${DOCKER_USERNAME}/apigateway:latest
    ports:
      - "8081:8081"
    depends_on:
      discoveryserver:
        condition: service_healthy
      redis-ktpm:
        condition: service_healthy
    volumes:
      - ./logs/apigateway:/logs
    environment:
      LOG_PATH: /logs
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8761/eureka
      SPRING_DATA_REDIS_HOST: redis-ktpm
      SPRING_DATA_REDIS_PORT: 6379
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - spring-net

  userservice:
    container_name: userservice
    image: ${DOCKER_USERNAME}/userservice:latest
    ports:
      - "9001:9001"
    depends_on:
      configserver:
        condition: service_healthy
      discoveryserver:
        condition: service_healthy
    volumes:
      - ./logs/userservice:/logs
    environment:
      LOG_PATH: /logs
      SPRING_DATASOURCE_URL: jdbc:sqlserver://52.77.85.156:1433;databaseName=UserDB;encrypt=false
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: TechGalaxy@12345
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8761/eureka
      SPRING_ZIPKIN_BASE-URL: http://zipkin:9411
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9001/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - spring-net

  productservice:
    container_name: productservice
    image: ${DOCKER_USERNAME}/productservice:latest
    ports:
      - "9002:9002"
    depends_on:
      configserver:
        condition: service_healthy
      discoveryserver:
        condition: service_healthy
      zipkin:
        condition: service_healthy
    volumes:
      - ./logs/productservice:/logs
    environment:
      LOG_PATH: /logs
      SPRING_DATASOURCE_URL: jdbc:sqlserver://52.77.85.156:1433;databaseName=ProductDB;encrypt=false
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: TechGalaxy@12345
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8761/eureka
      SPRING_ZIPKIN_BASE-URL: http://zipkin:9411
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9002/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - spring-net

  inventoryservice:
    container_name: inventoryservice
    image: ${DOCKER_USERNAME}/inventoryservice:latest
    ports:
      - "9006:9006"
    depends_on:
      configserver:
        condition: service_healthy
      discoveryserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./logs/inventoryservice:/logs
    environment:
      LOG_PATH: /logs
      SPRING_DATASOURCE_URL: jdbc:sqlserver://52.77.85.156:1433;databaseName=InventoryDB;encrypt=false
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: TechGalaxy@12345
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8761/eureka
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_ZIPKIN_BASE-URL: http://zipkin:9411
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9006/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - spring-net

  orderservice:
    container_name: orderservice
    image: ${DOCKER_USERNAME}/orderservice:latest
    ports:
      - "9003:9003"
    depends_on:
      configserver:
        condition: service_healthy
      discoveryserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis-ktpm:
        condition: service_healthy
    volumes:
      - ./logs/orderservice:/logs
    environment:
      LOG_PATH: /logs
      SPRING_DATASOURCE_URL: jdbc:sqlserver://52.77.85.156:1433;databaseName=OrderDB;encrypt=false
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: TechGalaxy@12345
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8761/eureka
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_DATA_REDIS_HOST: redis-ktpm
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_ZIPKIN_BASE-URL: http://zipkin:9411
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9003/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - spring-net

  paymentservice:
    container_name: paymentservice
    image: ${DOCKER_USERNAME}/paymentservice:latest
    ports:
      - "9005:9005"
    depends_on:
      configserver:
        condition: service_healthy
      discoveryserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./logs/paymentservice:/logs
    environment:
      LOG_PATH: /logs
      SPRING_DATASOURCE_URL: jdbc:sqlserver://52.77.85.156:1433;databaseName=PaymentDB;encrypt=false
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: TechGalaxy@12345
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8761/eureka
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_ZIPKIN_BASE-URL: http://zipkin:9411
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9005/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - spring-net

  notificationservice:
    container_name: notificationservice
    image: ${DOCKER_USERNAME}/notificationservice:latest
    ports:
      - "9004:9004"
    depends_on:
      configserver:
        condition: service_healthy
      discoveryserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./logs/notificationservice:/logs
    environment:
      LOG_PATH: /logs
      SPRING_DATASOURCE_URL: jdbc:sqlserver://52.77.85.156:1433;databaseName=NotificationDB;encrypt=false
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: TechGalaxy@12345
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8761/eureka
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_ZIPKIN_BASE-URL: http://zipkin:9411
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9004/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - spring-net


  recommendsservice:
    container_name: recommendService
    image: ${DOCKER_USERNAME}/RecommendService:latest
    ports:
      - "5000:5000"
    depends_on:
      discoveryserver:
        condition: service_healthy
    environment:
      EUREKA_SERVER: http://discoveryserver:8761/eureka
    restart: unless-stopped
    networks:
      - spring-net

  redis-ktpm:
    image: redis:alpine
    container_name: redis-ktpm
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge

volumes:
  redis-data:
