name: Docker Cleanup

on:
  workflow_run:
    workflows: ["Docker API Gateway Service Image CI/CD", "Docker Config Server Service Image CI/CD", "Docker Discovery Service Image CI/CD", "Docker Inventory Service Image CI/CD", "Docker Notification Service Image CI/CD", "Docker Order Service Image CI/CD", "Docker Payment Service Image CI/CD", "Docker Product Service Image CI/CD", "Docker User Service Image CI/CD"]
    types:
      - completed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Cleanup Docker
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker system prune -af
